version: "3.0"
services:
  aiui-y8-svc:
    container_name: aiui-y8-svc
    image: aiui-y8-svc:20231231
    environment:
      - AUTH_METHOD=NONE
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - ./best.pt:/root/best.pt
    ports:
      - 9999:9999
    networks:
      - backend

networks:
  backend:
    driver: bridge
