version: "3.0"
services:
  captcha-app:
    container_name: captcha-app
    image: captcha-app:20230512
    environment:
      - AUTH_METHOD=NONE
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - ./captcha_model.pt:/root/captcha_model.pt
      - ./bmcnn_model.pt:/root/bmcnn_model.pt
    ports:
      - 8888:8888
    networks:
      - backend

networks:
  backend:
    driver: bridge
