FROM python:3.9-slim-buster

RUN apt-get update

RUN apt-get -y install libgl1-mesa-glx
RUN apt-get -y install libglib2.0-0

RUN pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cpu
