version: "3.0"
services:
  aiui-db:
    container_name: aiui-db
    image: aiui:db-20231231
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
    command:
       --character-set-server=utf8
       --collation-server=utf8_unicode_ci
    volumes:
      - ./aiui-db:/var/lib/mysql
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 3306:3306
    networks:
      - backend

networks:
  backend:
    driver: bridge
