server:
  port: 8080

yolo:
  service:
    url: ${YOLO_SERVICE_URL:http://127.0.0.1:9999}

# BASIC, LDAP, NONE
auth:
  method: ${AUTH_METHOD:NONE}

upload:
  folder: ${UPLOAD_FOLD:c:/temp/}

spring:
  profiles:
    active: ${ACT_PROFILE:local}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#  datasource:
#    driver-class-name: ${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}
#    url: ${JDBC_URL:jdbc:mysql://172.25.58.71:3306/aidb?serverTimezone=UTC&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true} 
#    username: ${DB_USER:aichoi}
#    password: ${DB_PWD:aichoi}

#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate:
#        format_sql: true
#    hibernate:
#      ddl-auto: update
#    generate-ddl: false
#
#logging.level.org.hibernate.SQL: debug

logging:
  file:
    name: ${LOG_DIR:c:/work}/vision.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_DIR:c:/work}/llma_%d{yyyy-MM-dd}.%i.log
      max-history: 31

    
